### ISSUE TITLE
Espruino Web IDE Console not responding.

### ISSUE THREAD

**Issue by adishavit** [espruino/EspruinoBuilds#1]
Hi,

  I flashed a NodeMCU devboard with the latest firmware (using ESP8266Flasher.exe). 
I can connect to the board with the Web IDE and the blinking LED demo seems to work fine.

However, the console on the left does not respond to keyboard inputs not does it display any `print` calls.

Any suggestions? What am I doing wrong?

**Comment by nkolban** [comment]
Please create issues at the github repository for Espruino

https://github.com/espruino/Espruino/issues
