### ISSUE TITLE
ESP8266-01 and 433Mhz radio (transmit)

### ISSUE THREAD

**Issue by olliephillips** [espruino/EspruinoBuilds#3]
### Reference discussions in gitter with @tve

I'm trying to run a 433Mhz radio on ESP8266/Espruino. The aim is to control 433Mhz wireless plug sockets.

I have code that runs and triggers socket on Pico with 433Mhz transmitter. Same code will NOT work on ESP8266 with same 433Mhz transmitter. 

My boards are the "01" variant. 

I have used various builds since port project began. Current version I'm testing with is "espruino_1v81.tve_esp8266-flash-strings_662306b_esp8266.tgz". But issue has existed throughout.

My 433Mhz project relies on the Espruino method, "digitalPulse()"

Thinking/discussion around this topic on Gitter has so far implied ESP8266 has hardware timer constraints that may limit its application in areas that require precise, and in particular, very small/short timings. As well as 433Mhz I'm inferring that means projects base on infrared tranmission too. 

However, similar projects seem to exist for Arduino which would suggest hardware is not the constraint. An ESP8266 flashed with appropriate software seems able to use a 433Mhz radio to transmit to these RF controlled plug sockets. Link to video - https://www.youtube.com/watch?v=NAkyki615cY&feature=youtu.be

Of interest is that ESP8266 seems to be able to accurately record the signal from the remote control that came with the plug sockets.  I can replay the resulting binary code using a Pico and have it trigger the socket. Looking at the code involved in receiving those signals, I would suggest (though it is only a suggestion) that it also relies on an accurate hardware timer to record the code so that it can be replayed.

Latest discussion on gitter with @tve suggested the default logDebug setting of "true" may be a factor, but in later tests adding this has changed nothing.

My limited understanding of why Arduino projects might work while Espruino does not is that the former compiles to C++ while Espruino is still interpreted at runtime - so the issues are different and potentially more complex.

What bugs me is that ESP8266 via Espruino can record a signal I can reuse (on Pico), but seems incapable of sending same.

If I can provide more info let me know. Would love to put this to bed - one way or the other.

Some example transmit code. Works on Pico. Not ESP8266-01

```
require("ESP8266").logDebug(false);

var TX = D2; // On 8266
//var TX = A4; // On Pico

var newSend = [0.9, 0.3, 0.3, 0.9, 0.9, 0.3, 0.9, 0.3, 0.9, 0.3,0.3, 0.9,0.3, 0.9, 0.9, 0.3, 0.3, 0.9, 0.3, 0.9, 0.3, 0.9, 0.9, 0.3, 0.3, 0.9, 0.3, 0.9, 0.3, 0.9, 0.9, 0.3, 0.3, 0.9, 0.9, 0.3, 0.3, 0.9, 0.3, 0.9, 0.9, 0.3, 0.9, 0.3, 0.3, 0.9, 0.9, 0.3, 0.3, 0.9, 0.001];

function sendSignal() {
  var dP = digitalPulse;
  var interval = setInterval(function() {
  "compiled";  
  dP(TX, 1, newSend);
  if (times-- < 0) clearInterval(interval);
  }, 30);
}

setInterval(function(){
  console.log("Sending..");
  sendSignal();
}, 5000);

```

**Comment by tve** [comment]
Copied to https://github.com/espruino/Espruino/issues/735
